name: quote_generator

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Init
        uses: actions/checkout@v3.5.3

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1.5.0

      - name: Generate quote 1
        run: dart pub get

      - name: Generate quote 2
        run: dart format --output=none --set-exit-if-changed .

      - name: Generate quote 3
        run: dart analyze

      - name: Generate quote 4
        run: dart test

      - name: Update README.md
        run: |
          git config user.email "16353896+bhtri@users.noreply.github.com"
          git config user.name "bhtri"
          git add .
          git commit -m "Updated README.md" || echo "No changes to commit"
          git pull --rebase
          git push

      - name: Generate Profile Summary Cards
        uses: vn7n24fzkq/github-profile-summary-cards@v0.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_SECRET }}
        with:
          USERNAME: ${{ github.repository_owner }}

      - name: Make gitartwork SVG
        uses: jasineri/gitartwork@v1
        with:
          user_name: jasineri
          text: WDVQMJ7377

      - name: Make gitartwork SVG push action
        uses: jasineri/simple-push-action@v2

      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk@v2.2.1
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake.svg
          gif_out_path: dist/github-contribution-grid-snake.gif

      - name: Push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
