name: quote_generator

on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Generate quote
      uses: actions/checkout@v2
      uses: actions/setup-node@v1
      with:
        node-version: 12.16.1
      run: npm ci
      run: npm run generate

    - name: Update README.md
      run: |
        git config user.email "16353896+bhtri@users.noreply.github.com"
        git config user.name "bhtri"
        git add .
        git commit -m "Updated README.md" || echo "No changes to commit"
        git push

    - name: Generate Profile Summary Cards
      uses: vn7n24fzkq/github-profile-summary-cards@release
      env:
        GITHUB_TOKEN: ${{ secrets.MY_SECRET }}
      with:
        USERNAME: ${{ github.repository_owner }}

    - name: Generate github-contribution-grid-snake.svg
      uses: Platane/snk@master
      with:
        github_user_name: bhtri
        svg_out_path: dist/github-contribution-grid-snake.svg

    - name: Push github-contribution-grid-snake.svg to the output branch
      uses: crazy-max/ghaction-github-pages@v2.5.0
      with:
        target_branch: output
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
