name: quote_generator_dart

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: jasineri/gitartwork@v1
        with:
          user_name: ${{ github.repository_owner }}
          text: bhtri

      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - run: dart format --output=none --set-exit-if-changed .
      - run: dart analyze
      - run: dart bin/main.dart

      - name: Update README.md
        run: |
          git config user.email "16353896+bhtri@users.noreply.github.com"
          git config user.name "bhtri"
          git add .
          git commit -m "Updated README.md" || echo "No changes to commit"
          git pull --rebase
          git push

      - uses: vn7n24fzkq/github-profile-summary-cards@v0.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.MY_SECRET }}
        with:
          USERNAME: ${{ github.repository_owner }}

      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: crazy-max/ghaction-github-pages@v4.2.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
